DROP TABLE IF EXISTS Tweets;

CREATE TABLE TWEETS (
  user_id BIGINT PRIMARY KEY,
  user_name VARCHAR(20) NOT NULL,
  text VARCHAR(500) NOT NULL,
  locale VARCHAR(10) NOT NULL,
  valid BOOLEAN NOT NULL
);